kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/home/flying/.vfox/cache/java/v-17.0.2+8/java-17.0.2+8

version=2.11.2
group=de.miraculixx
projectName=Veinminer-Client
modid=veinminer_client
author=Miraculixx, Max Bossing
licence=AGPL 3.0
description=Client addon for Veinminer providing HUD overlays, hotkeys, and pattern selection

minecraftVersion=1.20.1
forgeVersion=1.20.1-47.3.12
mappingsVersion=1.20.1
kffVersion=4.11.0
